### ISSUE TITLE
Untranslated contents

### ISSUE THREAD

**Issue by milotype** [kimai/www.kimai.org#126]
**Problem**
Where/how to translate currently untranslated contents for localized web pages?

- [x] Contents (names and descriptions) of the **Features** list in the localized page [Home](https://www.kimai.org/hr/): _Mobile ready_, _Plugins_, etc.
- [x] Strings "Demo will be reinstalled in …" within the `<div class="card">` in the localized page [Demo](https://www.kimai.org/hr/demo.html)
- [ ] Tags in the localized page [News](https://www.kimai.org/hr/blog/) like `Announcement`, `Apps & Plugins` etc.
- [x] Tags in the localized page [Marketplace](https://www.kimai.org/hr/store/) like `plugin`, `development`, etc.
- [x] Prices in the page [Marketplace](https://www.kimai.org/hr/store/) should be formated with a space between the amount and currency, for instance **2,99 €**. The price "Free" should be translatable!

**Solution**
If possible, add a component or components to the project [Kimai - Time tracking](https://hosted.weblate.org/projects/kimai/) for the website contents.

**Comment by kevinpapst** [comment]
Hi @milotype - I took some time today to start making other pieces of the website translatable.

Unfortunately weblate is not an option currently, due to technical restrictions. I will give it a try in the future, but time is limited...

Anyway, today I started with the "features" section of the homepage, which was rather easy to do.
You can add your translations here: https://github.com/kimai/www.kimai.org/tree/master/_features/hr
The original content can be found here: https://github.com/kimai/www.kimai.org/tree/master/_includes/features

Two things you can do:
- change the title 
- replace the `{% include features/active-entries.md %}` with the actual translated content

**Comment by RaphaelLaurent** [comment]
Hi Kevin,

Thanks for the message, I will start translating the features in the next few days (I just created a fork).

**Comment by kevinpapst** [comment]
Hey you two 😄 

I had an inspiration today and found a way to add the main translations to weblate: 
https://hosted.weblate.org/projects/kimai/website/

I will have to do more refactorings to allow translating other components/store pages/menu ... but the first step is always the most complicated one and that was likely a success today.

There are some new translations in the main files, so you could give it a try at any time. I am really curious if it works as well as with Kimai itself.

**Comment by milotype** [comment]
@kevinpapst GREAT! I've just translated the Croatian part at https://hosted.weblate.org/projects/kimai/website/hr/. Good luck and I hope everything works fine.

**Comment by kevinpapst** [comment]
@milotype here is the first web late PR: https://github.com/kimai/www.kimai.org/pull/155/files

**Comment by kevinpapst** [comment]
Thanks to your continuous feedback, I refactored the website again and moved more translations to the Weblate component:
you can now edit the entire features list there and all menu names and titles.

Plus the "Demo will be reinstalled" string, which is currently untranslated

Croatian: https://hosted.weblate.org/translate/kimai/website/hr/?q=has:check
French: https://hosted.weblate.org/translate/kimai/website/fr/?q=has:check

I already received translations for other languages, but I cannot add them yet, because of all the other (page, store) files which are missing. I have to find a way to move those to Weblate as well, so we can edit at least all titles in there.
Thanks to you I see a big SEO potential lying around here... will push that topic further as soon as I find more time.

For now I will ignore all the other strings which are on pages, that only exist in english (documentation, news, v1 pages), but concentrate on the main pages.

**Comment by milotype** [comment]
@kevinpapst OK, Croatian is translated.
Please also check my comment at: https://hosted.weblate.org/translate/kimai/invoice-templates/hr/?q=has:comment#comments

**Comment by kevinpapst** [comment]
Done @milotype ... I have still a lot to learn about weblate 😳

**Comment by RaphaelLaurent** [comment]
French is also translated

**Comment by kevinpapst** [comment]
Today I merged a lot of changes. Just in case you have received too many Weblate emails today, you soon know why 😁 

While I was working on integrating Chinese translations, I found several places which were still untranslatable.

The files in this repo are more and more only empty placeholders to trigger the Jekyll build for this language, but are not meant for the actual translations any more. Also: applying changes to four (or more) languages started to be annoying, so I worked on more translatable elements. 
And as of today a lot of new elements are translatable through Weblate, e.g. shop title/intro/featured text

What is missing from the initial post are the translatable news categories. But news are english only, so I would ignore that point for now and simply close here!?!
