### ISSUE TITLE
Hashtag missing

### ISSUE THREAD

**Issue by cepheiden** [kimai/www.kimai.org#30]
i am trying to install kimai. 

but I miss the Hashtag administration. 
any Ideas?

**Comment by kevinpapst** [comment]
You are completely wrong here.
1. there is no hastag administration, please use the proper wording, otherwise we can't help
2. this is the Kimai website repository
3. [Kimai 1](https://github.com/kimai/kimai) or [Kimai 2](https://github.com/kevinpapst/kimai2)?

Don't answer here, open a new issue in the correct repository (see 3).
